#!/bin/bash

if [ $# -eq 1 -a "$1" == "--check" ] ; then
  node diagram.js
  git add diagram.md
  if ! git diff --cached --exit-code diagram.md ; then
    echo "Changes detected in diagram.md. Please run './diagram --write' and commit the results."
    exit 1
  fi
  exit 0
fi

if [ $# -eq 1 -a "$1" == "--write" ] ; then
  node diagram.js
  git add diagram.md
  git status diagram.md
  exit 0
fi

echo "Usage: './diagram --write' or './diagram --check'" >&2
exit 1
